package demo.development;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Planning implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Site Name")
   private java.lang.String siteName;
   @org.kie.api.definition.type.Label("Site Planning Id")
   private java.lang.String sitePlanningId;

   @org.kie.api.definition.type.Label(value = "Site Score")
   private java.lang.Integer siteScore;

   @org.kie.api.definition.type.Label(value = "Adjusted Score")
   private java.lang.Integer adjustedScore;

   public Planning()
   {
   }

   public java.lang.String getSiteName()
   {
      return this.siteName;
   }

   public void setSiteName(java.lang.String siteName)
   {
      this.siteName = siteName;
   }

   public java.lang.String getSitePlanningId()
   {
      return this.sitePlanningId;
   }

   public void setSitePlanningId(java.lang.String sitePlanningId)
   {
      this.sitePlanningId = sitePlanningId;
   }

   @Override
   public String toString()
   {
      return "[siteName=" + siteName + ", sitePlanningId=" + sitePlanningId + ", siteScore=" + siteScore + ", adjustedScore=" + adjustedScore + "]";
   }

   public java.lang.Integer getSiteScore()
   {
      return this.siteScore;
   }

   public void setSiteScore(java.lang.Integer siteScore)
   {
      this.siteScore = siteScore;
   }

   public java.lang.Integer getAdjustedScore()
   {
      return this.adjustedScore;
   }

   public void setAdjustedScore(java.lang.Integer adjustedScore)
   {
      this.adjustedScore = adjustedScore;
   }

   public Planning(java.lang.String siteName, java.lang.String sitePlanningId,
         java.lang.Integer siteScore, java.lang.Integer adjustedScore)
   {
      this.siteName = siteName;
      this.sitePlanningId = sitePlanningId;
      this.siteScore = siteScore;
      this.adjustedScore = adjustedScore;
   }

}