package demo.development;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ValidationError implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "VALIDATIONERROR_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "VALIDATIONERROR_ID_SEQ", name = "VALIDATIONERROR_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Description(value = "A validation error exists with a cause")
   @org.kie.api.definition.type.Label(value = "Cause")
   private java.lang.String cause;

   public ValidationError()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getCause()
   {
      return this.cause;
   }

   public void setCause(java.lang.String cause)
   {
      this.cause = cause;
   }

   public ValidationError(java.lang.Long id, java.lang.String cause)
   {
      this.id = id;
      this.cause = cause;
   }

}